#!/usr/bin/python
#
import os
import re
import datetime
import sys

version = "1.0"
script  = "updateRefDir.py"

localRefDir = "root/ref/"
refIndexFile = localRefDir + "index.html"

siteRefPath = "/ref/"

dir = localRefDir
extensions = [".html"]
patterns = [".+[[0-9A-Za-z]{6}"]

def getCurrentTime():
    now = datetime.datetime.now()
    return (now.strftime("%Y-%m-%d %H:%M:%S")) 

genDate = getCurrentTime()

indexPrefix = """<!DOCTYPE html PUBLIC '-//W3C//DTD HTML 4.01//EN'
'http://www.w3.org/TR/html4/strict.dtd''> 
<html>
    <head>
    </head>
    <body>
        <ul>
"""
indexPostfix = """        </ul>
        <p><i>Latest update: """ + genDate + """ - Generated by: """ + script + """, """ + version + """</i></p>
    </body>
</html>
"""

indexTemplate = """            <li><a href='%%URL%%'>%%FILENAME%%</a></li>
"""

def findFiles(base, extensions, filters):
    allList = getFiles(base)
    filtList = []
    for item in allList:
        if selector(item, extensions, filters):
            filtList.append(item)
    return sorted(filtList)

def getFiles(dirName):
    listOfFile = os.listdir(dirName)
    completeFileList = []
    for file in listOfFile:
        completePath = os.path.join(dirName, file)
        if completePath.startswith("./"):
            completePath = completePath[2:]
        if os.path.isdir(completePath):
            completeFileList = completeFileList + getFiles(completePath)
        else:
            completeFileList.append(completePath)
    return completeFileList
    
def selector(item, extensions, filters):
    splitItem = os.path.splitext(item)
    base = os.path.splitext(item)[0]
    ext  = os.path.splitext(item)[1]
#    print (" selector: " + base + " . " + ext)
    if extensions:
        if not ext in extensions:
#            print (" not in extensions: " + item)
            return False
##        else:
##            print (" in extensions: " + item  )
    if filters:
        found = False
        for filterPatt in  filters:
            print (" filt. " + filterPatt + " : " + base)
            if re.match(filterPatt, base):
                print ("  match: " + item)
                found = True
        return found
    return True


def getUrlPath(htmlFile):
    urlPath = ''   
    redirFile = open(htmlFile, 'r')

    lines = redirFile.readlines()
    for line in lines:
        line = line.rstrip()
        if (re.match("^\s+<meta http-equiv='Refresh' content=.0; url=", line)):
#            print("Found: '" + line + "'")
            urlPath = re.sub("\s+<meta http-equiv='Refresh' content=.0; url='/", "", line)
            urlPath = re.sub("'\" />", "", urlPath)
    redirFile.close()
    return urlPath

fileList = findFiles(dir, extensions, patterns)

indexFile = open(refIndexFile, 'w')
indexFile.write(indexPrefix)

for refFile in fileList:
    print("refFile: " + refFile)  
    url = getUrlPath(refFile)
    print(url)
    filename = re.sub("\S+/", "", url)
    filename = re.sub(".html", "", filename)
    print(filename)
    itemLine = indexTemplate
    itemLine = re.sub('%%URL%%', url, itemLine)
    itemLine = re.sub('%%FILENAME%%', filename, itemLine)
    indexFile.write(itemLine)
    
indexFile.write(indexPostfix)
indexFile.close()
